name: Manual CI / Test Runner

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment for tests'
        required: true
        default: stage
        type: choice
        options:
          - stage
          - prod
      runner:
        description: 'Execution method for tests'
        required: true
        default: GitHub runner
        type: choice
        options:
          - GitHub runner
          - Docker container

jobs:
  setup-environment:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      ENV: ${{ steps.set-env.outputs.ENV }}
      RUNNER: ${{ steps.set-env.outputs.RUNNER }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Set environment outputs
        id: set-env
        run: |
          echo "ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "RUNNER=${{ github.event.inputs.runner }}" >> $GITHUB_ENV
          echo "::set-output name=ENV::${{ github.event.inputs.environment }}"
          echo "::set-output name=RUNNER::${{ github.event.inputs.runner }}"

  execute-tests:
    name: Execute Tests
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Copy environment file
        run: cp .env.${{ needs.build.outputs.ENV }} .env

      - name: Run tests on GitHub runner
        if: ${{ needs.build.outputs.RUNNER == 'GitHub runner' }}
        run: npm run test:${{ needs.build.outputs.ENV }}

      - name: Run tests in Docker container
        if: ${{ needs.build.outputs.RUNNER == 'Docker container' }}
        run: npm run docker:test:${{ needs.build.outputs.ENV }}

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            ./logs
            ./output/allure-results
          if-no-files-found: ignore

  generate-and-publish-allure:
    name: Generate and Publish Allure Report
    runs-on: ubuntu-latest
    needs: execute-tests
    if: always()
    permissions:
      pages: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Download Allure results from tests artifacts 
        uses: actions/download-artifact@v4 
        with: 
          name: test-artifacts
      
      - name: Generate Allure Report
        run: npm run allure:generate

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./output/allure-report